### ISSUE TITLE
Error: Process completed with exit code 1.

### ISSUE THREAD

**Issue by AyasakiAtre** [enpitsuLin/skland-daily-attendance#11]
Run pnpm attendance

> skland-daily-attendance@1.0.0 attendance /home/runner/work/skland-daily-attendance/skland-daily-attendance
> tsx main.ts

/home/runner/work/skland-daily-attendance/skland-daily-attendance/main.ts:111
    const { code } = await auth(token)
            ^

TypeError: Cannot destructure property 'code' of '(intermediate value)' as it is undefined.
    at doAttendanceForAccount (/home/runner/work/skland-daily-attendance/skland-daily-attendance/main.ts:111:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
    at <anonymous> (/home/runner/work/skland-daily-attendance/skland-daily-attendance/main.ts:152:1)

Node.js v1[8](https://github.com/AyasakiAtre/skland-daily-attendance/actions/runs/6953388889/job/18918429976#step:8:9).[18](https://github.com/AyasakiAtre/skland-daily-attendance/actions/runs/6953388889/job/18918429976#step:8:19).2
 ELIFECYCLE  Command failed with exit code 1.
Error: Process completed with exit code 1.
今早刚出的问题

**Comment by enpitsuLin** [comment]
看了下可能是你的 cred 出了点问题，

**Comment by AyasakiAtre** [comment]
> 看了下可能是你的 cred 出了点问题，

重新fork了一个突然又行了，估计是昨天在网页上登录过森空岛的原因
