### ISSUE TITLE
attendance 不再自动执行

### ISSUE THREAD

**Issue by Wuweimo9893466** [enpitsuLin/skland-daily-attendance#19]
现在只能手动点run workflow了，不能每天自动执行，有老哥遇到这种状况吗

**Comment by enpitsuLin** [comment]
看起来是仓库太久没有改动自动被 github disabled 了，actions 左边选择 attendance 后右边应该有类似 enabled 的提示 
![image](https://github.com/enpitsuLin/skland-daily-attendance/assets/29378026/deadcc02-5da3-4904-bba2-12d20332bff2)

**Comment by Wuweimo9893466** [comment]
请问没有这条提示应该怎么办呢？
![5c863807be54748af0f0bfb94a55e05](https://github.com/enpitsuLin/skland-daily-attendance/assets/67273524/c0130fff-b543-45b9-9da4-15254ab441a9)

**Comment by enpitsuLin** [comment]
🤡那就不知道具体什么原因了，或许你可以删了仓库再frok一次
