### ISSUE TITLE
getBinding返回值异常

### ISSUE THREAD

**Issue by SilentC1ty** [enpitsuLin/skland-daily-attendance#2]
{ code: 10000, message: '签名验证失败' }
我原来用的另一个自动签到脚本也一样的异常= =之前一直好的

**Comment by enpitsuLin** [comment]
鹰角突然需要一个额外的 header 测试了下修复了 

但是 action 应该还是会报错

因为 获取奖励的格式也变了 如果有多余的账号并且有能力修改的可以帮忙改一下这部分

**Comment by SilentC1ty** [comment]
看下我在另一个issue的回复，我在签到的接口参考其他header加了个platform就好了，但我今天手动签到过了，所以直接显示的重复签到的提示

**Comment by enpitsuLin** [comment]
@SilentC1ty 这个问题已经修复了

🤣但是得明天看看获取的奖励格式有啥不一样
