### ISSUE TITLE
签到执行出错

### ISSUE THREAD

**Issue by enpitsuLin** [enpitsuLin/skland-daily-attendance#22]
应该是笨笨鹰角换字段名称或者是什么其他变动了，不过甲流刚好可能暂时处理不了先放放

**Comment by moeyua** [comment]
大概是 Token 过期了，重新获取一下 Token 就好了，#20 
不过最近会很频繁的出现这个问题，不确定有没有什么保活的方法

**Comment by enpitsuLin** [comment]
@moeyua 看起来是有改动 [参考](https://github.com/Maojuan-lang/SenKongDao#%E6%96%B0%E7%89%88%E6%9C%AC%E8%84%9A%E6%9C%AC%E7%9A%84%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E%E9%87%8D%E8%A6%81%E5%8F%98%E5%8A%A8cred%E5%8F%98%E4%B8%BAtoken)

**Comment by Hakuin123** [comment]
感觉频繁出问题可能是因为先后在浏览器和森空岛app登录账号，而森空岛似乎并不支持多端登录的样子…
~~个人的解决办法：水个帖子里面插入链接跳转到api（？）~~

**Comment by moeyua** [comment]
> 感觉频繁出问题可能是因为先后在浏览器和森空岛app登录账号，而森空岛似乎并不支持多端登录的样子… ~个人的解决办法：水个帖子里面插入链接跳转到api（？）~

我这里没有登录过森空岛的 APP，大概可能不是这个原因？

**Comment by Hakuin123** [comment]
啊嘞，那就不清楚了（）果咩（
总之咱是遇到过这样的情况来着



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月2日(周二) 上午9:36
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [enpitsuLin/skland-daily-attendance] 签到执行出错 (Issue #22)




  
感觉频繁出问题可能是因为先后在浏览器和森空岛app登录账号，而森空岛似乎并不支持多端登录的样子… 个人的解决办法：水个帖子里面插入链接跳转到api（？）
  
我这里没有登录过森空岛的 APP，大概可能不是这个原因？

**Comment by JerryLikePie** [comment]
也遇到了这个问题，而且第二天就又可以了，只是偶尔出错，隔个三天fail三天的样子，所以感觉不只是token的问题

**Comment by enpitsuLin** [comment]
> 也遇到了这个问题，而且第二天就又可以了，只是偶尔出错，隔个三天fail三天的样子，所以感觉不只是token的问题

确实，直接重跑也是能用的说明实际上 token 并没有问题

**Comment by roo12589** [comment]
好像是因为没指定content-type? #24

**Comment by Gezhe14** [comment]
> 好像是因为没指定content-type? #24

我fork了你的还是不行=-=，而且今天重跑和重新添加token都签到不了了

**Comment by Morris-Lucifer** [comment]
> > 好像是因为没指定content-type? #24
> 
> 我fork了你的还是不行=-=，而且今天重跑和重新添加token都签到不了了

我也是重跑和重新添加token都签到不了，而且以前出现这种报错的时候通常是官网token过期要重新输入密码登录，今天打开官网都不用重新登录还是报错
