### ISSUE TITLE
pnpm报错

### ISSUE THREAD

**Issue by LockRim** [enpitsuLin/skland-daily-attendance#34]
今天突然出现的错误
---
Run pnpm/action-setup@v2
  with:
    version: 8
    run_install: false
    dest: ~/setup-pnpm
    package_json_file: package.json
    standalone: false
Running self-installer...
   WARN  GET https://registry.npmjs.org/pnpm error (ERR_INVALID_THIS). Will retry in 10 seconds. [2](https://github.com/LockRim/skland-daily-attendance/actions/runs/9799436956/job/27068509506#step:4:2) retries left.
   WARN  GET https://registry.npmjs.org/pnpm error (ERR_INVALID_THIS). Will retry in 1 minute. 1 retries left.
   ERR_PNPM_META_FETCH_FAIL  GET https://registry.npmjs.org/pnpm: Value of "this" must be of type URLSearchParams
Error: Something went wrong, self-installer exits with code 1
Installation Completed!

**Comment by enpitsuLin** [comment]
#30 解决了这个问题 https://github.com/enpitsuLin/skland-daily-attendance/actions/runs/9804068481
