### ISSUE TITLE
增加 Cloudflare Warp+ 代理防止 IP 被风控

### ISSUE THREAD

**Issue by enpitsuLin** [enpitsuLin/skland-daily-attendance#40]
确认是被风控了，可能段时间内需要手动签到或者开 MAA 的时候用下 MAA 的森空岛签到吧

鹰角游戏不好好做，天天搞这些😅道高一尺魔高一丈懂不懂啊，哥们又不是攻击你。

**Comment by Rayon642** [comment]
确实很无语，换代理改下ip也只能生效一周左右
话说MAA的森空岛签到是什么意思？利用它的开始前/结束后脚本执行功能吗？

**Comment by enpitsuLin** [comment]
> 确实很无语，换代理改下token也只能生效一周左右
> 话说MAA的森空岛签到是什么意思？利用它的开始前/结束后脚本执行功能吗？

https://github.com/MaaXYZ/MaaAssistantSkland 这个基于模拟点击的，不太清楚具体使用方式

但是现在应该所有的直接用过请求api的方式签到的都有概率被风控
