### ISSUE TITLE
执行报错 403 Forbidden

### ISSUE THREAD

**Issue by Montaro2017** [enpitsuLin/skland-daily-attendance#45]
```
FetchError: [POST] "https://zonai.skland.com/api/v1/game/attendance": 403 Forbidden
```
![image](https://github.com/user-attachments/assets/194fc7e0-48bc-46c1-9e31-591fae352f48)

**Comment by Jack5013** [comment]
请问有解决办法吗，我也是这个样子

**Comment by enpitsuLin** [comment]
见 https://github.com/enpitsuLin/skland-daily-attendance/issues/49#issuecomment-2323156128
