### ISSUE TITLE
405 悲 好像风控加回来了

### ISSUE THREAD

**Issue by YoungHKe** [enpitsuLin/skland-daily-attendance#50]
> skland-daily-attendance@1.0.0 attendance /home/runner/work/skland-daily-attendance/skland-daily-attendance
> tsx main.ts
node:internal/process/task_queues:95
    runMicrotasks();
    ^
FetchError: [POST] "https://zonai.skland.com/api/v1/user/auth/generate_cred_by_code": 405 Not Allowed
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async $fetch2 (file:///home/runner/work/skland-daily-attendance/skland-daily-attendance/node_modules/.pnpm/ofetch@1.3.4/node_modules/ofetch/dist/shared/ofetch.37386b05.mjs:268:[15](https://github.com/YoungHKe/skland-daily-attendance/actions/runs/10799811414/job/29970970515#step:8:15))
    at signIn (/home/runner/work/skland-daily-attendance/skland-daily-attendance/src/api/skland.ts:21:[16](https://github.com/YoungHKe/skland-daily-attendance/actions/runs/10799811414/job/29970970515#step:8:16))
    at doAttendanceForAccount (/home/runner/work/skland-daily-attendance/skland-daily-attendance/src/index.ts:[17](https://github.com/YoungHKe/skland-daily-attendance/actions/runs/10799811414/job/29970970515#step:8:17):38)
    at async Promise.all (index 0)
    at <anonymous> (/home/runner/work/skland-daily-attendance/skland-daily-attendance/main.ts:12:1)
Node.js v[18](https://github.com/YoungHKe/skland-daily-attendance/actions/runs/10799811414/job/29970970515#step:8:18).18.2
 ELIFECYCLE  Command failed with exit code 1.
Error: Process completed with exit code 1.

**Comment by sss20081** [comment]
这两天我也遇到了同样的错误

**Comment by enpitsuLin** [comment]
应该只是丫丁抽风了这几天恢复了

**Comment by SherkeyXD** [comment]
现在貌似有ip检测了

**Comment by enpitsuLin** [comment]
今天第一次跑也报错了，应该还是间歇性抽风，或者真的加上 ip 检测？还要观察一段时间

**Comment by PianCat** [comment]
> 今天第一次跑也报错了，应该还是间歇性抽风，或者真的加上 ip 检测？还要观察一段时间

确定了有IP检测了，拿家宽跑的，一天六号，喜提IP封禁，只能用App跑了

**Comment by Hakuin123** [comment]
感觉看脸，昨天第一次失败第二次成功，今天跑了四次才成(*ﾟーﾟ)

**Comment by Jack5013** [comment]
我今天是先用的香港节点打开github重试一直失败，换日本然后成功了，不知道有没有关系

**Comment by Hakuin123** [comment]
> 我今天（9.20）是先用的香港节点打开github重试一直失败，换日本然后成功了，不知道有没有关系

兄啊，GitHub Action是在GitHub在自己的服务器上面跑的（）和你访问GitHub网页的位置没什么关系

**Comment by luoxiaoxin123** [comment]
今天我也遇到了

**Comment by Tsuk1ko** [comment]
看了下，https://zonai.skland.com/api/v1/user/auth/generate_cred_by_code 估计是接了阿里云[Web 应用防火墙](https://www.alibabacloud.com/help/zh/waf/)

请求 header 里有 `ali_sign_whash` `wtoken` 两个，少任意一个都会被拦截，而且看着应该很难绕过

好消息是可以换用网页端接口 https://zonai.skland.com/web/v1/user/auth/generate_cred_by_code ，参数一致

坏消息是这个接口会校验 did，而且我逆向很菜找不到生成逻辑，但是自己抓个可以拿来用，但不知道是否可持续

**Comment by enpitsuLin** [comment]
> 看了下，[zonai.skland.com/api/v1/user/auth/generate_cred_by_code](https://zonai.skland.com/api/v1/user/auth/generate_cred_by_code) 估计是接了阿里云[Web 应用防火墙](https://www.alibabacloud.com/help/zh/waf/)
> 
> 请求 header 里有 `ali_sign_whash` `wtoken` 两个，少任意一个都会被拦截，而且看着应该很难绕过
> 
> 好消息是可以换用网页端接口 [zonai.skland.com/web/v1/user/auth/generate_cred_by_code](https://zonai.skland.com/web/v1/user/auth/generate_cred_by_code) ，参数一致
> 
> 坏消息是这个接口会校验 did，而且我逆向很菜找不到生成逻辑，但是自己抓个可以拿来用，但不知道是否可持续

国庆可以看下这个内容，或者有别的项目处理了这个可以CV一下😋

**Comment by Tsuk1ko** [comment]
> 国庆可以看下这个内容，或者有别的项目处理了这个可以CV一下😋

和之前基本一致，只是 header 中需要提供合法 did，但对于公开项目来说放自己的担心有潜在的隐私问题，也可以考虑由用户提供

目前我有个公共服务直接用了我自己的 did，还在观察能不能持久使用

https://github.com/arkntools/proxy-worker/blob/fc0a130e3a378b9607743588beb33b3b8710c8b3/src/skland.ts#L30-L47

该签到项目我也自己改了下，目前运行良好🥹

![image](https://github.com/user-attachments/assets/f141562f-4693-4a58-a538-d6e4a1ded7e6)

**Comment by PianCat** [comment]
> > 国庆可以看下这个内容，或者有别的项目处理了这个可以CV一下😋
> 
> 和之前基本一致，只是 header 中需要提供合法 did，但对于公开项目来说放自己的担心有潜在的隐私问题，也可以考虑由用户提供
> 
> 目前我有个公共服务直接用了我自己的 did，还在观察能不能持久使用
> 
> https://github.com/arkntools/proxy-worker/blob/fc0a130e3a378b9607743588beb33b3b8710c8b3/src/skland.ts#L30-L47
> 
> 该签到项目我也自己改了下，目前运行良好🥹
> 
> ![image](https://private-user-images.githubusercontent.com/24877906/371378691-f141562f-4693-4a58-a538-d6e4a1ded7e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0MzQxNTgsIm5iZiI6MTcyNzQzMzg1OCwicGF0aCI6Ii8yNDg3NzkwNi8zNzEzNzg2OTEtZjE0MTU2MmYtNDY5My00YTU4LWE1MzgtZDZlNGExZGVkN2U2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI3VDEwNDQxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0N2MzYTUwYzhhMWZkNWRlMTQyMDM5ODYwMjUxNWFmOTM1MmI0NGQyNGQyMjQ4ZjU2YzYxNzIyNzM1ZjBjOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5JwZZvCq-OVgApVUth4WTkeeo75YFzInDN6VsimGops)

did是怎么获取的呢？

**Comment by Tsuk1ko** [comment]
@PianCat 有很多接口都会发送 did，搜一下就行

![image](https://github.com/user-attachments/assets/caa3e24f-fb34-49fe-b2dd-7c38a369af15)

**Comment by ztmzzz** [comment]
did是localStorage的SK_SHUMEI_DEVICE_ID_KEY。但是还附带timestamp，不知道多久会过期。

**Comment by Tsuk1ko** [comment]
确实，我都忘了去这里找，根据这个线索倒是找到来源了

```js
window._smConf = {
  organization: 'UWXspnCCJN4sfYlNfqps',
  appId: 'default',
  publicKey: 'MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCmxMNr7n8ZeT0tE1R9j/mPixoinPkeM+k4VGIn/s0k7N5rJAfnZ0eMER+QhwFvshzo0LNmeUkpR8uIlU/GEVr8mN28sKmwd2gpygqj0ePnBmOW4v0ZVwbSYK+izkhVFk2V/doLoMbWy6b+UnA8mkjvg0iYWRByfRsK2gdl7llqCwIDAQAB',
  protocol: 'https',
};
```

加载 https://bbs.hycdn.cn/public/skland/others/skland-bbs/60e9c30fb0b1d1ca574c4522ca06fc7b.js 之后可以调用

```js
window.SMSdk.getDeviceId()
```

可以得到设备id

估计是这个东西 https://help.ishumei.com/docs/tw/sdk/web/developDoc

**Comment by ztmzzz** [comment]
写个网页接入数美sdk确实能获取到DeviceId。但是刷新网页后DeviceId就会改变，不知道获取到的能坚持多久。
而用puppeteer这样的方案感觉有点重。

**Comment by Tsuk1ko** [comment]
试了下可以在 node 环境下获取设备ID，不用靠 headless browser 了，可参考该 demo

https://github.com/Tsuk1ko/node-skland-did-demo

**Comment by enpitsuLin** [comment]
#54 解决了
