### ISSUE TITLE
405报错

### ISSUE THREAD

**Issue by luoxiaoxin123** [enpitsuLin/skland-daily-attendance#53]
rt
![1ff0c93c-1ee8-4cca-84ea-970c1bc622fc](https://github.com/user-attachments/assets/d94304d4-0a6b-43b0-8e23-17fde31aeb1a)

**Comment by luoxiaoxin123** [comment]
![image](https://github.com/user-attachments/assets/7abd8e99-f6ef-4004-b8c6-ed6422b03787)

**Comment by luoxiaoxin123** [comment]
![image](https://github.com/user-attachments/assets/259356f8-62c9-4151-941e-0f8f1680364a)

**Comment by jcjrobert** [comment]
不知道IP限制多久，要是永久那就只能模拟操作了

**Comment by JJS-CN** [comment]
风控了, generate_cred_by_code直接报405

**Comment by Montaro2017** [comment]
现在基本不能用了

**Comment by ala-404** [comment]
找了一圈，看大佬说是鹰角换接口了

**Comment by xubaiwang** [comment]
粗略看了下网页版的代码，`generate_cred_by_code` 还在代码里，应该是没换接口吧。这几天有空再仔细看看。
