### ISSUE TITLE
请求支持登岛检票

### ISSUE THREAD

**Issue by Hakuin123** [enpitsuLin/skland-daily-attendance#7]
简简单单抓个包：
https://zonai.skland.com/api/v1/score/checkin
方法：POST

请求示例：
{
  "gameId": 1
}
gameId为对应版区的ID，对照关系如下：
1：明日方舟
2：来自星辰
3：终末地
4：泡姆泡姆
100：纳斯特港

响应示例：
{
  "code": 0,
  "message": "OK"
}

应该挺好实现吧…？（手动狗头）不过咱不会结合GitHub Action…拜托了xwx

**Comment by enpitsuLin** [comment]
有点不明白这个是干什么的，能解释一下吗，如果也是类似每日签到一样的任务可能可以扩大下这个项目的适用范围

**Comment by Hakuin123** [comment]
相当于是深空岛内各个版区的每日签到，效果是水经验（）

![Screenshot_20231116_171138_edit_7790167444995.jpg](https://github.com/enpitsuLin/skland-daily-attendance/assets/108911712/fc3ed212-df44-4db8-a82e-0847cae54779)


![Screenshot_20231116_170826_com.hypergryph.skland.jpg](https://github.com/enpitsuLin/skland-daily-attendance/assets/108911712/9efd0255-0523-4650-ab36-7bba6c8672b9)

希望大大能支持呀
